name: Show "on issue" event details

on:
  issues:
    types:
      - opened

jobs:
  show-on-issue-details:
    runs-on: ubuntu-latest
    steps:
      - name: Show environment
        run: |
          echo "::debug::Issue number: ${{ github.event.issue.number }}"

          echo "::debug::Environment variables"
          set|sort

          echo "::debug::github context"
          echo "::debug::${{ toJson(github) }}"

          echo "::debug::env context"
          echo "::debug::${{ toJson(env) }}"

          echo "::debug::job context"
          echo "::debug::${{ toJson(job) }}"

          echo "::debug::steps context"
          echo "::debug::${{ toJson(steps) }}"

          echo "::debug::runner context"
          echo "::debug::${{ toJson(runner) }}"

          echo "::debug::strategy context"
          echo "::debug::${{ toJson(strategy) }}"

          echo "::debug::matrix context"
          echo "::debug::${{ toJson(matrix) }}"

          echo "::debug::needs context"
          echo "::debug::${{ toJson(needs) }}"

          echo "::debug::Procenv"
          sudo apt -y install procenv
          procenv
